baseURL = 'https://whateverzpy.github.io/Zlog/'
languageCode = 'zh-CN'
title = 'WhateverZ'
theme = "hugo-theme-stack"
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"

[Params]
  favicon = "/Zlog/favicon.png"

[Params.widgets]
  page = [
    {type = "toc"},
  ]
  homepage = [
    {type = "search"},
  ]

[Params.Sidebar]
  avatar = { src = "/avatar.png" }
  emoji = "😪"
  subtitle = "Zlog"

[Params.Footer]
  since = 2024
  customText = "L'amor che move il sole e l'altre stelle."

[Params.Article]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.extensions.passthrough]
      enable = true
      delimiters.block = [
        ["\\[", "\\]"],
        ["$$", "$$"]
      ]
      delimiters.inline = [
        ["\\(", "\\)"],
        ["$", "$"]
      ]
  [markup.highlight]
    noClasses = false

[languages.zh-cn.params]
  reading_speed = 200