baseURL = 'https://whateverzpy.github.io'
languageCode = 'zh-CN'
title = 'WhateverZ'
theme = "hugo-theme-stack"
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"

[Params]
  favicon = "/favicon.png"

[Params.widgets]
  page = [
    {type = "toc"},
    {type = "search"}
  ]

[Params.Sidebar]
  avatar = { src = "/avatar.png" }
  emoji = "😪"
  subtitle = "Zlog"

[Params.Footer]
  since = 2024
  customText = "L'amor che move il sole e l'altre stelle."

[menus]
  [[menus.main]]
    name = '主页'
    title = '主页'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = '文章'
    title = '文章'
    pageRef = '/post'
    weight = 20
  [[menus.main]]
    name = '关于'
    title = '关于'
    pageRef = '/about'
    weight = 30

[Params.Article]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.extensions.passthrough]
      enable = true
      delimiters.block = [
        ["\\[", "\\]"],
        ["$$", "$$"]
      ]
      delimiters.inline = [
        ["\\(", "\\)"],
        ["$", "$"]
      ]

[languages.zh-cn.params]
  reading_speed = 200