baseURL = 'https://whateverzpy.github.io/Zlog/'
languageCode = 'zh-CN'
title = 'WhateverZ'
theme = "hugo-theme-stack"
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true

[Params]
  favicon = "/Zlog/favicon.png"

[Params.DateFormat]
  published = "2006-01-02"
  lastUpdated = "2006-01-02 15:04 -07:00"

[Params.widgets]
  page = [
    {type = "toc"},
  ]
  homepage = [
    {type = "search"},
  ]

[Params.Sidebar]
  avatar = { src = "/avatar.png" }
  emoji = "😪"
  subtitle = "Zlog"

[Params.Footer]
  since = 2024
  customText = "L'amor che move il sole e l'altre stelle."

[Params.Article]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      delimiters.block = [
        ["\\[", "\\]"],
        ["$$", "$$"]
      ]
      delimiters.inline = [
        ["\\(", "\\)"],
        ["$", "$"]
      ]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.highlight]
    noClasses = false

[languages.zh-cn.params]
  reading_speed = 300

[menu]
  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/whateverzpy"
    [menu.social.params]
      icon = "brand-github"
  [[menu.social]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    [menu.social.params]
      icon = "rss"


[outputs]
  home = ["html", "rss"]
  section = ["html", "rss"]